### ISSUE TITLE
QQ

### ISSUE THREAD

**Issue by mgaulton** [philcryer/prickly-pete#1]
I love this idea. I did something simpler with NATing iptables rules to redirect bad actors to the honeybots without having the report the services.

I'd love to have all of the stuffs dumping logs to ELK in a way to build a dashboard for analysis. Any thoughts on the best way to accomplish this?

**Comment by philcryer** [comment]
lol, just seeing this, bad on me, sorry, but I'm sure it'd be a fun enhancement. Hey, we've got a few days before DEF CON
