### ISSUE TITLE
docker-compose.yml is invalid

### ISSUE THREAD

**Issue by fmaurice** [philcryer/prickly-pete#2]
Hello,
The file contains tab characters instead of spaces.
Also I had to add :
Version "3.1" in the first line, to allow docker-compose working.

My version of docker-compose is 1.25.0
Docker version is 20.10.5

Thanks !

Franck

**Comment by philcryer** [comment]
I'm apparently awful at github, I'm just seeing this, thanks for the feedback, I'm going to update it and test it out now. Appreciagte your feedback!
